- lib/runner/extensions/event.command.js
- lib/runner/extensions/item.command.js
- lib/runner/extensions/request.command.js
- lib/runner/extensions/waterfall.command.js
- lib/runner/run.js
- npm/test-integration.js
- package.json
- test/integration/runner-spec.test.js
This slightly non-atomic PR. I request that you review the PR by seeing commit diffs one after the other.
Note that, next round is to separate waterfall and iteration
> Separate Item Execution Extension - Simplified Waterfall

- lib/runner/extensions/item.command.js
- lib/runner/extensions/request.command.js
- npm/test.js
- test/integration/stop-on-error-request-spec.test.js
- test/integration/stop-on-error-script-spec.test.js
We now stop the run gracefully
> implemented the stop-on-runner flag

- lib/runner/cursor.js
- package.json
- test/integration/stop-on-error-multiple-iterations-spec.test.js
- test/system/nsp.test.js
> This fixes stopOnError which throws in case we have multiple iterations

- lib/requester/request-wrapper.js
- lib/requester/requester.js
```js
...
runner.run(collection, {
requester: {
proxyManager: ProxyManager,
}
}
})
...
```
where,
```js
/**
*  @params url  [Postman Request Url](http://www.postmanlabs.com/postman-collection/Url.html)
*  @params cb  function
*/
ProxyManager.getProxyConfiguration = function (url, cb) {
return cb(null, {proxy: proxyURL, tunnel: false});
}
```
> Provided the ability to pass the proxy to the runtime

- lib/runner/extensions/request.command.js
- test/integration-sinon/url-sanity-before-request.spec.js
- test/integration-sinon/url-sanity-before-request.test.js
which is a solution for:
* postmanlabs/postman-app-support#2276
* postmanlabs/postman-app-support#2285
> ensure that we parse the url again after resolving variables

- .eslintrc
- package.json
* [JSDoc](https://github.com/gajus/eslint-plugin-jsdoc)
* [Lodash](https://github.com/eslint-plugins/eslint-plugin-lodash)
* [Mocha](https://github.com/lo1tuma/eslint-plugin-mocha)
> Added ESLint plugins

- package.json
- test/integration/sanity/query-parameters.test.js
Which contains a bugfix for UTF-8 encoding.
> Updated postman-request

- lib/uvm/host.js
- lib/uvm/vm-execute.js
Remove all injected objects from globals, and instead use variable references to them.
> remove everything from the global scope

- test/system/repository.test.js
> Added npm script structure test

- appveyor.yml
- test/system/appveyor-yml.test.js
Let's have this one go out and see how it behaves...
> Fixed appveyor builds

- lib/requester/requester.js
- test/integration/sanity/http-reason-phrases.test.js
* cleanup of the requester code
> * Ensure that the response reason phrase is used if available

- package.json
Real diff: https://github.com/postmanlabs/postman-request/commit/e9651274f8823e270dbddc48ca3dbbae37e14dd8
> Updated request module version

- lib/uvm/libraries.js
- lib/uvm/vm-execute.js
- lib/uvm/vm-require.js
- package.json
- test/system/repository.test.js
Also added a system test to ensure `lodash3` sanity.
> Replaced Lodash with Lodash3 in sandbox

- lib/backpack/index.js
- lib/requester/request-wrapper.js
- lib/requester/requester.js
- lib/requester/util.js
- lib/runner/cursor.js
- lib/runner/index.js
- lib/runner/instruction.js
- lib/runner/run.js
> Switched to _.assign from _.assignIn

- lib/requester/requester.js
- lib/runner/extensions/request.command.js
- lib/runner/request-helpers.js
- test/integration-legacy/requester-spec.test.js
- test/integration/sanity/certificate.test.js
Requester no longer accepts things it does not need to.
> removed all deprecated options

- README.md
- lib/requester/requester.js
- lib/requester/util.js
- test/integration/sanity/cookie-handling.test.js
- test/integration/sanity/get-req-bodies.test.js
Sending is disabled by default. This is a behavioral change, @shamasis
> Added an option to enable or disable sending of bodies with GET requests

- test/integration/sanity/case-insen-header-sandbox.test.js
Newman equivalent: https://github.com/postmanlabs/newman/blob/develop/test/integration/case-insen-header-sandbox.postman_collection.json
> Added case insensitive header integration tests

- test/integration/sanity/clear-vars-sandbox.test.js
Newman equivalent: https://github.com/postmanlabs/newman/blob/develop/test/integration/clear-vars-sandbox.postman_collection.json
> Added variable clearing sandbox integration tests

- test/integration/sanity/dynamic-variable-replacement-sandbox.test.js
Newman equivalent: https://github.com/postmanlabs/newman/blob/develop/test/integration/dynamic-var-replacement.postman_collection.json
> Added Dynamic variable replacement integration tests

- test/integration/sanity/hawk-auth.test.js
Newman equivalent: https://github.com/postmanlabs/newman/blob/develop/test/integration/hawk-auth-test.postman_collection.json
> Added hawk auth integration tests

- test/integration/sanity/head-request.test.js
Newman equivalent: https://github.com/postmanlabs/newman/blob/develop/test/integration/head-requests.postman_collection.json
> Added HEAD request integration tests

- test/integration/sanity/multi-value-data.test.js
Newman equivalent: https://github.com/postmanlabs/newman/blob/develop/test/integration/multi-value-data.postman_collection.json
> Added multi valued data integration tests

- test/integration/sanity/multiple-value-form-data.test.js
Newman equivalent: https://github.com/postmanlabs/newman/blob/develop/test/integration/multiple-form-values.postman_collection.json
> Added multiple valued form data integration tests

- test/integration/sanity/gzip-encoding.test.js
Newman equivalent: https://github.com/postmanlabs/newman/blob/develop/test/integration/newman-gzip-test.postman_collection.json
> Added gzip encoding integration tests

- test/integration/sanity/oauth1-var-in-url-params.test.js
Newman equivalent: https://github.com/postmanlabs/newman/blob/develop/test/integration/oauth1-var-in-url-params.postman_collection.json
> Added OAuth url params integration tests

- test/integration/sanity/sugar-js.test.js
Newman equivalent: https://github.com/postmanlabs/newman/blob/develop/test/integration/prototype-check.postman_collection.json
> Added Sugarjs sandbox integration tests

- test/integration/sanity/request-name-script.test.js
Newman equivalent: https://github.com/postmanlabs/newman/blob/develop/test/integration/request-name-in-script.postman_collection.json
> Added request name script integration tests

- test/integration/sanity/sandbox-libraries.test.js
Newman equivalent: https://github.com/postmanlabs/newman/blob/develop/test/integration/super-sandbox-test.postman_collection.json
> Added Sandbox library integration tests

- test/integration/sanity/var-replacement.test.js
Newman equivalent: https://github.com/postmanlabs/newman/blob/develop/test/integration/var-replacement.postman_collection.json
> Added variable replacement integration tests

- test/integration/sanity/v2-regression.test.js
Newman equivalent: https://github.com/postmanlabs/newman/tree/develop/test/integration/v2-regression-tests
> Added Newman V2 regression integration tests

- test/integration/sanity/slashed-variable.test.js
Newman equivalent: https://github.com/postmanlabs/newman/tree/develop/test/integration/slashed-variable-names
> Added slashed variable integration tests

- test/integration/sanity/redirect.test.js
Newman equivalent: https://github.com/postmanlabs/newman/tree/develop/test/integration/redirect-test
> Added redirect integration tests

- test/integration/sanity/var-overrides.test.js
Newman equivalent: https://github.com/postmanlabs/newman/tree/develop/test/integration/globals-env-data-files
> Added variable override integration tests

- test/integration/sanity/esc-formdata.test.js
Newman equivalent: https://github.com/postmanlabs/newman/tree/develop/test/integration/esc-formdata
> Added escaped formdata integration tests

- test/integration/sanity/data-file-var-replacement.test.js
Newman equivalent: https://github.com/postmanlabs/newman/tree/develop/test/integration/data-file-var-replacement
> Added data file variable replacement integration tests

- test/integration/sanity/econnrefused.test.js
- test/integration/sanity/malformed.test.js
- test/integration/sanity/script-syntax-error.test.js
- test/integration/sanity/server-ssl.test.js
* Malformed variables
* Server side SSL errors
* `ECONNREFUSED` checks
* Pre-request and request script syntax errors
> Added runtime v5 regression tests

- package.json
Closes #240
https://greenkeeper.io/
> fix(package): update postman-collection to version 1.2.1

- lib/runner/extensions/request.command.js
- test/integration-legacy/requester-spec.test.js
- test/integration/sanity/certificate.test.js
- test/integration/sanity/get-req-bodies.test.js
- test/integration/sanity/request-timeout.test.js
> Fixed the beforeRequest and request trigger behavior

- test/integration/sanity/response-size.test.js
> added a test to check for response sizes in a couple of different cases

- package.json
> fix(package): update postman-collection to version 1.2.5

- package.json
> fix(package): update postman-collection to version 1.2.8

- package.json
Lodash3 has now been shifted to postman-sandbox
> Pruned unused dependency

- README.md
- npm/test-coverage.js
- package.json
TODO: Integrate https://codecov.io/ for better integration.
> Cumulative test coverage

- test/integration/auth-methods/basic.test.js
- test/integration/auth-methods/digest.test.js
- test/integration/auth-methods/hawk.test.js
- test/integration/auth-methods/oauth1.test.js
TODO: Streamline OAuth 2.0 flows.
> Auth integration tests

- test/unit/requester-util.test.js
- test/unit/runner-util.test.js
* Requester util
* Runner util
> Added util unit tests

- package.json
> Update jsdoc to version 3.5.3

- package.json
> Update sinon to version 2.4.1

- lib/requester/util.js
- test/unit/requester-util.test.js
With this change, headers with falsy keys will not be included in the final headers object.
This addresses postmanlabs/newman#1154
> Invalid header key fix

- lib/authorizer/digest.js
- test/integration/auth-methods/digest.test.js
- test/unit/auth-handlers.test.js
> Make sure `sign` in digest auth handler sends the error to callback

- lib/runner/extensions/control.command.js
- test/integration/sanity/control-flow.test.js
Fixes a case where a user tries to abort a run after pausing it.
> fix a bug where not able to abort the run after pausing it

- .eslintrc
- lib/authorizer/aws4.js
- lib/authorizer/basic.js
- lib/authorizer/bearer.js
- lib/authorizer/digest.js
- lib/authorizer/hawk.js
- lib/authorizer/index.js
- lib/authorizer/noauth.js
- lib/authorizer/ntlm.js
- lib/authorizer/oauth1.js
- lib/authorizer/oauth2.js
- package.json
- test/fixtures/auth-manifest-schema.json
- test/integration/auth-methods/manifest.test.js
> Add auth manifest definition and schema

- lib/authorizer/digest.js
- test/fixtures/auth-requests.json
- test/integration/auth-methods/digest.test.js
- test/unit/auth-handlers.test.js
Fixes Github Issue: https://github.com/postmanlabs/postman-app-support/issues/2941
> Fix digest auth (MD5-sess)

- package.json
> Update ajv to version 5.2.5

- lib/runner/extensions/event.command.js
- lib/runner/extensions/http-request.command.js
- lib/runner/extensions/item.command.js
- lib/runner/extensions/waterfall.command.js
- lib/runner/request-helpers-presend.js
- package.json
- test/integration/inherited-entities/pm-variables.test.js
- test/integration/inherited-entities/variables.test.js
~Blocked on https://github.com/postmanlabs/postman-sandbox/pull/223~
> Persist pm.variables across scripts

- package.json
This version bump comes with the following changes:
* Code tested on Node v8
* `postman-collection` bumped to v3.0.2
> Bumped postman-sandbox to v3.0.0-beta.2

- CHANGELOG.md
- README.md
- lib/authorizer/ntlm.js
- lib/requester/requester-pool.js
- lib/requester/requester.js
- lib/requester/util.js
- test/integration/sanity/dns-lookup.test.js
- test/integration/sanity/restricted-addresses.test.js
- test/unit/requester-util.test.js
This only adds support for resolving hostnames by using an object.
How that object is created is currently left to discuss (Should app do it or runtime?)
> Add support for custom dns lookup

- lib/runner/index.js
- test/unit/runner.test.js
- Fixes entrypoint error message issues in newman discussed [here](https://github.com/postmanlabs/newman/pull/1326).
> Fixed entrypoint error message, added test

- package.json
> chore(package): update eslint-plugin-lodash to version 2.6.1

- .nsprc
- lib/requester/core.js
- npm/test-system.js
- test/system/nsp.test.js
- test/unit/requester-core.test.js
Discovered by @ahmad-511 in https://github.com/postmanlabs/postman-app-support/issues/4397.
> Allowed whitelisted keywords in request body keys

- package.json
> chore(package): update colors to version 1.2.1

- package.json
> chore(package): update colors to version 1.2.3

- package.json
> chore(package): update sinon to version 5.0.9

- package.json
> chore(package): update eslint-plugin-jsdoc to version 3.7.1

- package.json
> fix(package): update postman-sandbox to version 3.1.1

- lib/runner/extensions/event.command.js
- test/integration/sanity/variable-changes.test.js
* Update to sandbox that now provides variable changes within the script execution
* Use the variable changes for internally updating variables
> Consume sandbox with variable change tracking enabled

- lib/runner/request-helpers-presend.js
- test/integration/sanity/certificate.test.js
FIxes postmanlabs/postman-app-support#3251
> Avoid forwarding certificate lookup error

- package.json
> chore(package): update ajv to version 6.5.3

- package-lock.json
- test/integration/sanity/timeouts/sync-scripts.test.js
> Fix flaky tests

- appveyor.yml
- package-lock.json
- package.json
- test/integration/request-body/protocolProfileBehavior.test.js
Verifies postmanlabs/postman-request/pull/23
>  Added tests for protocolProfileBehavior using HEAD & Custom request method

- npm/test-system.js
- package-lock.json
- package.json
- test/.eslintrc
- test/system/appveyor-yml.test.js
- test/system/editorconfig.test.js
- test/system/jsdoc-config.test.js
- test/system/repository.test.js
- test/system/travis-yml.test.js
- Use chai expect assertions
- Add global expect for System test
> Migrate System Tests to Chai

- npm/test-unit.js
- test/unit/auth-handlers.test.js
- test/unit/auth-interface.test.js
- test/unit/auth-loader.test.js
- test/unit/authorizer-request.test.js
- test/unit/backpack-ensure.test.js
- test/unit/backpack-multiback.test.js
- test/unit/backpack-normalise.test.js
- test/unit/backpack-timeback.test.js
- test/unit/extract-runnable-items.test.js
- test/unit/replay-controller.test.js
- test/unit/requester-core.test.js
- test/unit/run.test.js
- test/unit/runner-cursor-resolve.js
- test/unit/runner-cursor.test.js
- test/unit/runner-timings.test.js
- test/unit/runner-util.test.js
- test/unit/runner.test.js
- Use chai expect assertions
- Add chai expect for unit test
> Migrate Unit Tests to Chai

- test/integration-legacy/abort-on-error-request-spec.test.js
- test/integration-legacy/abort-on-error-script-spec.test.js
- test/integration-legacy/abort-on-failure-script-spec.test.js
- test/integration-legacy/delay-spec.test.js
- test/integration-legacy/ipv6-localhost-spec.test.js
- test/integration-legacy/requester-spec.test.js
- test/integration-legacy/runner-spec.test.js
- test/integration-legacy/stop-on-error-multiple-iterations-spec.test.js
- test/integration-legacy/stop-on-error-request-spec.test.js
- test/integration-legacy/stop-on-error-script-spec.test.js
- test/integration-legacy/stop-on-failure-spec.test.js
- test/integration-legacy/uvm-spec.test.js
> Migrate Integration Legacy Tests to chai

- test/integration/auth-methods/basic.test.js
- test/integration/auth-methods/bearer-token.test.js
- test/integration/auth-methods/control-flow/errors.test.js
- test/integration/auth-methods/control-flow/typical.test.js
- test/integration/auth-methods/digest.test.js
- test/integration/auth-methods/hawk.test.js
- test/integration/auth-methods/manifest.test.js
- test/integration/auth-methods/ntlm.test.js
- test/integration/auth-methods/oauth1.test.js
> Migrate Integration Auth Methods Tests to chai

- test/integration/file-uploads/request-body.test.js
- test/integration/inherited-entities/auth.test.js
- test/integration/inherited-entities/events.test.js
- test/integration/inherited-entities/pm-variables.test.js
- test/integration/inherited-entities/variables.test.js
- test/integration/options-delay/wait-state-change-event-item.test.js
- test/integration/options-delay/wait-state-change-event-iteration.test.js
- test/integration/request-body/protocolProfileBehavior.test.js
- test/integration/request-flow/intermediate-requests.test.js
- test/integration/request-flow/pm-send-request-cookies.test.js
- test/integration/request-flow/replays-spec.test.js
- test/integration/request-flow/requests-from-sandbox.test.js
> Migrate Integration File Uploads Tests to Chai

- test/integration/sanity/econnrefused.test.js
- test/integration/sanity/esc-formdata.test.js
- test/integration/sanity/file-uploads.test.js
- test/integration/sanity/gzip-encoding.test.js
- test/integration/sanity/hawk-auth.test.js
- test/integration/sanity/head-request.test.js
- test/integration/sanity/http-methods.test.js
- test/integration/sanity/http-reason-phrases.test.js
- test/integration/sanity/malformed.test.js
- test/integration/sanity/multi-level-folder-sanity.test.js
- test/integration/sanity/multi-value-data.test.js
- test/integration/sanity/multi-value-response-headers.test.js
- test/integration/sanity/multiple-value-form-data.test.js
- test/integration/sanity/oauth1-var-in-url-params.test.js
> Migrate Integration Sanity Tests -2 to chai

- test/integration/sanity/proxy-http-vars.test.js
- test/integration/sanity/proxy-http.test.js
- test/integration/sanity/query-parameters.test.js
- test/integration/sanity/redirect.test.js
- test/integration/sanity/request-errors.test.js
- test/integration/sanity/request-name-script.test.js
- test/integration/sanity/response-callback.test.js
- test/integration/sanity/response-size.test.js
- test/integration/sanity/restricted-addresses.test.js
- test/integration/sanity/sandbox-libraries.test.js
- test/integration/sanity/sandbox-test-object.test.js
- test/integration/sanity/script-result.test.js
- test/integration/sanity/script-syntax-error.test.js
> Migrate Integration Sanity Tests -3 to chai

- test/integration/bootstrap.js
- test/integration/sanity/server-ssl.test.js
- test/integration/sanity/set-next-request.test.js
- test/integration/sanity/simple-sanity.test.js
- test/integration/sanity/slashed-variable.test.js
- test/integration/sanity/sugar-js.test.js
- test/integration/sanity/systemproxy.test.js
- test/integration/sanity/url-sanity-before-request.test.js
- test/integration/sanity/uvm-globals-this.test.js
- test/integration/sanity/v2-regression.test.js
- test/integration/sanity/var-overrides.test.js
- test/integration/sanity/var-replacement.test.js
- test/integration/sanity/variable-changes.test.js
> Migrate Integration Sanity Tests -4 to chai

- lib/authorizer/hawk.js
- package-lock.json
- package.json
- test/system/repository.test.js
Discovered in https://github.com/postmanlabs/newman/issues/1771
More context: https://github.com/request/request/issues/2831
> Hawk renaissance

- CHANGELOG.md
- README.md
- lib/requester/core.js
- lib/requester/requester-pool.js
- test/integration/requester-spec/redirect.test.js
- test/unit/requester-core.test.js
Added:
- followOriginalHttpMethod
- maxRedirects
- removeRefererHeader
> Added additional requester options for redirects

- README.md
- lib/requester/core.js
- lib/requester/requester-pool.js
- test/integration/requester-spec/redirect.test.js
- test/unit/requester-core.test.js
`removeRefererHeader` -> `removeRefererHeaderOnRedirect`
> Rename requester option for removing referer header

- .travis.yml
- package-lock.json
- package.json
- test/integration/protocol-profile-behavior/disableBodyPruning.test.js
- test/integration/protocol-profile-behavior/sanity.test.js
- test/integration/requester-spec/redirect.test.js
- test/integration/sanity/certificate.test.js
- test/integration/sanity/content-type-in-form-data.test.js
- test/integration/sanity/http-methods.test.js
- test/integration/sanity/http-reason-phrases.test.js
- test/integration/sanity/multi-value-response-headers.test.js
- test/integration/sanity/redirect.test.js
- test/system/travis-yml.test.js
- Force close local server
- Add Node v4 back to Travis
> Fix flaky integration tests

- test/fixtures/server.js
- test/integration/protocol-profile-behavior/sanity.test.js
- test/integration/sanity/certificate.test.js
Removed duplicate code for local SSL server from test files and added it in server.js module.
> Added SSL server to separate module in tests

- test/fixtures/server.js
- test/integration/request-flow/headers.test.js
- test/integration/sanity/content-type-in-form-data.test.js
- test/integration/sanity/form-data-order.test.js
- test/integration/sanity/http-reason-phrases.test.js
- test/integration/sanity/multi-value-response-headers.test.js
Created wrapper for HTTP server in server.js and used that in tests.
> Added HTTP server to module server.js

- lib/runner/extensions/event.command.js
- test/integration/sanity/control-flow.test.js
Refer: https://github.com/postmanlabs/postman-app-support/issues/5799
> Handle undefined in interrupted script execution

- package-lock.json
- package.json
> Greenkeeper/ajv 6.8.1

- lib/requester/requester.js
- test/integration/request-flow/headers.test.js
- test/integration/requester-spec/redirect.test.js
- test/integration/sanity/request-size.test.js
Closes https://github.com/postmanlabs/postman-collection/pull/785
> Add system headers to request

- CHANGELOG.yaml
- README.md
- lib/requester/requester.js
- lib/runner/extensions/http-request.command.js
- lib/runner/extensions/request.command.js
- package-lock.json
- package.json
- test/integration/requester-spec/timing.test.js
- Added history in request and response callback
- Moved timings out of response
> Add history in request and response callback

- package-lock.json
- package.json
- test/integration/sanity/proxy-http.test.js
Refer: https://github.com/postmanlabs/postman-runtime/pull/775/
> Update proxy auth test

- lib/requester/core-body-builder.js
- lib/requester/core.js
- package-lock.json
- package.json
- test/fixtures/server.js
- test/integration/request body/graphql.test.js
- test/integration/sanity/http-reason-phrases.test.js
> Handle GraphQL RequestBody

- lib/runner/extensions/event.command.js
- package-lock.json
- package.json
- test/integration/sandbox-libraries/pm.test.js
Passed argument to callback of pm.sendRequest() for cookies.
> Pass cookies in callback of pm.sendRequest()

- CHANGELOG.yaml
- lib/requester/core.js
- test/integration/request-flow/invalid-url.test.js
Regression From: https://github.com/postmanlabs/postman-runtime/pull/804
Refer:
https://github.com/postmanlabs/postman-app-support/issues/6533
https://github.com/postmanlabs/postman-app-support/issues/6558
> Handle Invalid URL

- lib/runner/extensions/http-request.command.js
- package-lock.json
- package.json
Reverts postmanlabs/postman-runtime#836
> Revert "Update async to the latest version 🚀"

- CHANGELOG.yaml
- README.md
- lib/requester/request-wrapper.js
- lib/requester/requester.js
- lib/runner/extensions/http-request.command.js
- test/integration/runner-spec/responseStart.test.js
- Added `responseStart` trigger which maps to requester `response` event
- Callback arguments: error, cursor, trace, response, cookies
TODO:
> Added responseStart trigger

- README.md
- lib/requester/requester.js
- lib/runner/extensions/http-request.command.js
- test/integration/runner-spec/responseStart.test.js
>  Added history in responseStart callback

- CHANGELOG.yaml
- lib/requester/core-body-builder.js
- lib/requester/core.js
- package-lock.json
- package.json
- test/integration/file-uploads/request-body.test.js
- test/integration/request-body/body-options.test.js
- test/integration/sanity/http-methods.test.js
- test/unit/requester-core.test.js
Adding support for Body Option Storage.
> Adding support for body option

- lib/runner/extensions/item.command.js
- package-lock.json
- package.json
- test/integration/sanity/variable-changes.test.js
- Added support for `pm.collectionVariables `
- Bump `postman-sandbox` dependency
> Added support for collection variables mutations tracking

- CHANGELOG.yaml
- lib/requester/core-body-builder.js
- test/integration/request-body/form-data.test.js
- Added check on form-data value in body builder.
Solves:
postmanlabs/postman-app-support#6180
Todo:
> Fixed crashing of runtime because of invalid form-data value

- CHANGELOG.yaml
- lib/authorizer/aws4.js
- lib/authorizer/edgegrid.js
- lib/authorizer/hawk.js
- test/integration/auth-methods/edgegrid.test.js
Ref: https://github.com/postmanlabs/postman-app-support/issues/7220
> Fix crashing of runtime for binary request body with AWS/Hawk/EdgeGrid auth

- CHANGELOG.yaml
- lib/authorizer/basic.js
- package-lock.json
- package.json
- test/unit/auth-handlers.test.js
Solves: https://github.com/postmanlabs/postman-app-support/issues/4070
> Unicode support for Basic Auth helper

- CHANGELOG.yaml
- lib/requester/core.js
- test/fixtures/server.js
- test/integration/sanity/proxy-http.test.js
Solves: https://github.com/postmanlabs/postman-app-support/issues/5626
> Fix lookup function binding for requests with proxy

- CHANGELOG.yaml
- lib/requester/core.js
- package-lock.json
- package.json
- test/integration-legacy/requester-spec.test.js
- test/integration/request-flow/headers.test.js
- test/integration/sanity/brotli-encoding.test.js
Enables option to accept and decompress brotli response and update `postman-request` dependency
> Add support for brotli decompression

- lib/requester/core.js
- package-lock.json
- package.json
- test/integration/protocol-profile-behavior/disabledSystemHeaders.test.js
- test/integration/request-body/form-data.test.js
- test/unit/requester-core.test.js
Add `disabledSystemHeaders` protocol profile behavior to disable sending system added headers.
> Add `disabledSystemHeaders` protocol profile behavior

- CHANGELOG.yaml
- README.md
- lib/requester/core.js
- lib/requester/requester-pool.js
- test/integration/requester-spec/agent.test.js
- test/unit/requester-core.test.js
> Added `agent` requester option to define a custom requesting agent

- CHANGELOG.yaml
- lib/requester/core.js
- package-lock.json
- package.json
- test/integration/sanity/response-status-message.test.js
Added `statusMessageEncoding` option to decode status message with specific encoding. 
All the status messages will now be decoded using `utf8` character encoding.
> Added `statusMessageEncoding` option

- docs/protocol-profile-behavior.md
Added `disabledSystemHeaders` config to the documentation of profile-protocol-behaviour
> Updated profile-protocol-behaviour.md 

- lib/requester/requester.js
- test/integration/sanity/url-sanity-before-request.test.js
Spotted while setting up a monitor in the app.
> fix: Typo extenstions for extensions

- CHANGELOG.yaml
- lib/runner/extensions/item.command.js
- test/integration/mutations/request.test.js
ref: https://github.com/postmanlabs/postman-app-support/issues/10368
> Added the support for mutable auth

- CHANGELOG.yaml
- lib/authorizer/jwt.js
- test/integration/auth-methods/jwt.test.js
Added support for allowing empty header prefix in JWT Auth 
Issue - https://github.com/postmanlabs/postman-app-support/issues/11841
> Add support for empty header prefix in JWT

- CHANGELOG.yaml
- lib/requester/dry-run.js
- lib/runner/request-helpers-presend.js
- test/integration/dry-run/raw-body-sanitization.test.js
- test/integration/request-body/json-with-comment.test.js
Fixed the issue where the raw language is undefined but the raw content is present and content type header is json.
> Strip comments for JSON `Content-Type`

- CHANGELOG.yaml
- lib/runner/extensions/event.command.js
- lib/runner/extensions/item.command.js
- package-lock.json
- package.json
- test/integration/request-flow/skip-execution-from-sandbox.test.js
Added support for `pm.execution.skipRequest()`
> Added support for skipping request execution through script

- lib/requester/core.js
- lib/requester/requester-pool.js
- package-lock.json
- package.json
- test/integration/requester-spec/agentIdleTimout.test.js
Exposed `agentIdleTimeout` option from postman-request
> Added agent idle timeout configuration
