lib/requester/util.js
package.json
test/integration/requester-spec.test.js
test/system/nsp.test.js

Currently, if the request body is empty, runtime still adds a header for form-data (the form-data boundary).
This PR fixes this.

Don't send empty request bodies

---

lib/requester/util.js

Ensures that "request" creates URL encoded formdata or querystring as
```
foo=bar&foo=baz
``` 
instead of 
```
foo[0]=bar&foo[1]=baz
```

ensure XHR compatible url-encoding of parameters

---

lib/requester/browser/request.js

This ensures that the browser correctly sends duplicate urlencoded body parameters

fixed handling of duplicate url-encoded bodies in the browser requester

---

lib/uvm/browser/sandbox-bus-start.js
lib/uvm/postman-api.js

A flawed check for value caused the value to not be set as a string if it is `false`. That is now corrected.

ensure that 'false' is casted to a string when using postman api

---

lib/requester/requester.js

`postman-request` sometimes changes headers. 
For example, if the content type is set to `formdata`, and the request already contains a `content-type` header set to `something`, it will be replaced with `multipart/formdata` + boundary. This behavior is good, and expected.
These changes made by `postman-request` were not being bubbled up from runtime before. This change ensures that they are.

ensure that correct sent headers are bubbled up from the request

---

lib/requester/browser/request.js

This fixes a bug which causes duplicate content type to be added sometimes.

ensure that we don't override content type if one is already given

---

CHANGELOG.md
lib/runner/extensions/event.command.js
lib/runner/extensions/request.command.js
lib/runner/extensions/waterfall.command.js
package.json
test/integration/sanity/query-parameters.test.js
test/integration/sanity/simple-sanity.test.js
test/integration/sanity/url-sanity-before-request.test.js

**This is a breaking API. So, merge it when you're ready to release v3.**
- this PR now expects globals and environments to be either sent as `VariableScope` or as in a format that `VariableScope` recognises
- this PR tries to do minimal change while enabling this feature and as such, code might appear hacky. the changes are contained within event and request commands

Using VariableScope instead of normal objects for Environment and Globals

---

package.json

Thanks to @jaydeep17 for his comment: [yarnpkg/yarn#739 (comment)](https://github.com/yarnpkg/yarn/issues/739#issuecomment-255598619)
This change allows installing this package (or a parent) with yarn.

Remove non-existing directories from `package.json`

---

test/integration-legacy/abort-on-error-request-spec.test.js
test/integration-legacy/abort-on-error-script-spec.test.js
test/integration-legacy/abort-on-failure-script-spec.test.js
test/integration-legacy/delay-spec.test.js
test/integration-legacy/ipv6-localhost-spec.test.js
test/integration-legacy/requester-spec.test.js
test/integration-legacy/runner-spec.test.js
test/integration-legacy/stop-on-error-multiple-iterations-spec.test.js
test/integration-legacy/stop-on-error-request-spec.test.js
test/integration-legacy/stop-on-error-script-spec.test.js
test/integration-legacy/stop-on-failure-spec.test.js
test/integration-legacy/uvm-spec.test.js

* Prevents multi callback errors from masking the actual test errors.
* Saves repetitive debugging effort.

Improved legacy integration tests

---

lib/requester/browser/request.js

This ensures that the Chrome does not spew out warnings/errors about setting Host and User-Agent headers, which ensures that Sentry does not get flooded.
There is no impact/change to the functionality.

do not try to set blacklisted headers on Chrome

---

lib/requester/browser/request.js

Headers were not sent when we have host in the headers list.

Used _.includes in blackisting the headers

---

README.md
npm/test-integration-newman.js
package.json

This PR adds a new test command: `npm run test-integration-newman`.
This is not executed as part of npm test and instead it is meant to be executed on demand

Added integration tests that fetch latest newman and run test with runtime replaced in it.

---

lib/requester/request-wrapper.js
lib/requester/requester.js
test/integration/sanity/certificate.test.js
test/integration/sanity/proxy-http.test.js

1. Uses `CertificateList` to resolve for a certificate.
2. Adds proxy information back to request.
Depends on [postman-collection#288](https://github.com/postmanlabs/postman-collection/pull/288) and [postman-collection#286](https://github.com/postmanlabs/postman-collection/pull/286)

Use `CertificateList` to resolve certificate if available

---

lib/requester/request-wrapper.js
test/integration/sanity/certificate.test.js

1. Fix typo in error handling
2. Fix usage of `async.mapValues`
3. Fix tests to fail if certificate is invalid

Fix issue in setting certificate file contents

---

lib/requester/request-wrapper.js

This makes sure we don't pass through the code for setting proxy when a match is not found.

Set search result to falsey value on setProxy

---

lib/runner/extensions/event.command.js
lib/runner/extensions/waterfall.command.js
package.json
test/integration-legacy/abort-on-error-request-spec.test.js
test/integration-legacy/abort-on-error-script-spec.test.js
test/integration-legacy/abort-on-failure-script-spec.test.js
test/integration-legacy/delay-spec.test.js
test/integration-legacy/requester-spec.test.js
test/integration-legacy/runner-spec.test.js
test/integration-legacy/stop-on-error-multiple-iterations-spec.test.js
test/integration-legacy/stop-on-error-request-spec.test.js
test/integration-legacy/stop-on-error-script-spec.test.js
test/integration-legacy/stop-on-failure-spec.test.js
test/integration-legacy/uvm-spec.test.js
test/integration/sanity/case-insen-header-sandbox.test.js
test/integration/sanity/clear-vars-sandbox.test.js
test/integration/sanity/cookie-handling.test.js
test/integration/sanity/file-uploads.test.js
test/integration/sanity/multi-value-data.test.js
test/integration/sanity/request-name-script.test.js
test/integration/sanity/sandbox-libraries.test.js
test/integration/sanity/sandbox-test-object.test.js
test/integration/sanity/sugar-js.test.js
test/integration/sanity/v2-regression.test.js
test/integration/sanity/var-overrides.test.js

* updated postProcessContext to process test failures correctly from the new execution object
* updated set next request logic to account for the new execution object
* fixed tests

Properly update to postman-sandbox v2.x (tests and all)

---

lib/runner/extensions/event.command.js
test/integration/sanity/clear-vars-sandbox.test.js
test/integration/sanity/malformed.test.js
test/integration/sanity/script-result.test.js

Ensures that the Script Results are consistent with the rest of the SDK events API.

ensure that we bubble up sdk instances, not serialized POJOs

---

package.json
test/integration/sanity/file-uploads.test.js

To be merged after `postman-request@2.81.1-postman.2` has been released and merged into this.

Added integration test for binary file upload content-length

---

lib/authorizer/index.js
lib/requester/index.js
lib/requester/requester-pool.js
lib/requester/requester.js
lib/runner/extensions/event.command.js
lib/runner/extensions/request.command.js
test/integration/sanity/cookie-handling.test.js
test/unit/authorizer-sanity.test.js

The premise of this PR comes from the bug where cookie jar was not persistent across requests.
Creating new instances of Requester whenever needed caused to not be able to store common stuff across requesters. This is still a temporary measure. 
For example, a reference to cookie jar could not be re-used.
Long Term: Down the line, CookieJar store would be forwarded to the request library after embedding the requester fully into `postman-request` as such, like sandbox, moving requester completely out into a separate external module.

Adds concept of RequesterPool to persist options

---

lib/requester/request-wrapper.js

Unless the value of tunnel is explicitly set to true, determine it from the type of request URL
If the URL is secure (https) set the tunnel value to true
In the App, we want to support a single global proxy server definition which can support both http and https requests.
If we don't do this then users won't be able to use the global proxy if their proxy server does not support tunnel for HTTP requests

Set the tunnel value from the type of request URL

---

.gitignore
.npmignore

As JetBrains IDEs use .idea for IDE specific settings, Visual Studio Code uses .vscode.
These two one-line changes just add add .vscode to the .gitignore and .npmignore lists.

Add Visual Studio Code .vscode to ignore lists

---

lib/runner/extensions/event.command.js
lib/runner/extensions/request.command.js
lib/runner/instruction.js
lib/runner/run.js
package.json
test/integration/request-flow/requests-from-sandbox.test.js

Queue `pm.sendRequest` through `request` command instead of sending the request over directly. This handles variable, proxy, and certificate resolution.

Queue `pm.sendRequest` through `request` command

---

lib/requester/requester.js
test/integration/request-flow/requests-from-sandbox.test.js
test/integration/sanity/url-sanity-before-request.test.js

`util.getRequestOptions` internally called `url.getHost` which errored out for empty host. `url.getHost` should not have errored in the first place, raised a [PR](https://github.com/postmanlabs/postman-collection/pull/443) for that as well.
Plus it doesn't make sense to proceed with `requester.request` when the `url` is empty. Hence added a bail out for this case.

Make sure empty Urls do not break runs

---

lib/authorizer/auth-interface.js
test/unit/auth-interface.test.js

This will also convert the property to system property (will add system: true)
This is needed for 2 reasons
- App sets the parameters as empty string which are not set by the user
- Exported collections have parameters as empty string

Allow updation of user properties when the value is empty string

---

lib/authorizer/ntlm.js
lib/authorizer/oauth2.js
test/unit/auth-handlers.test.js

1. remove redundant `get` operation
2. update a parameter name from `url` to `queryParams`

Fix minor issues in NTLM and Oauth-2

---

test/integration/sanity/script-timeouts/sync.test.js

For some reason, breached timeouts with synchronous scripts are flaky when tested on Windows.

Temporarily skip timeout test for windows

---

lib/authorizer/digest.js
test/integration/auth-methods/digest.test.js
test/unit/auth-handlers.test.js

1. Takes `qop` and `opaque` from the `www-authenticate` header from the server's response
2. Auto-generate `clientNonce`
3. `nonceCount` is fixed to 0000001
4. Added support for auth-int

Support qop, clientNonce, nonceCount and opaque fields

---

lib/runner/request-helpers-presend.js

The fix has been moved upstream

Remove workaround for variable resolution `toObjectResolved`

---

.nsprc
test/system/nsp.test.js

`postman-collection` is using `8fold-marked` in beta version and we are using that beta version in runtime. There is no need to exclude `postman-collection` from nsp check.

Avoid excluding postman-collection from nsp check

---

lib/runner/index.js
test/unit/runner.test.js

* Default timeouts are set if user provided timeout is missing/null/undefined
* To clear a timeout, 0 should be sent as timeout value
* Negative timeout values are treated as no timeout

Improvements to `timeout` value normalization

---

CHANGELOG.md
lib/authorizer/digest.js
test/integration/auth-methods/digest.test.js

Digest auth now does not retry when all the required auth parameters were already present in the first request sent
Required parameters are defined by those sent by the server in the authorization header.
So this can vary from server to server.

Digest auth retry logic updated

---

lib/runner/extensions/http-request.command.js
lib/runner/replay-controller.js

We no longer need to do this, as SDK allows to resolve objects without parents.

Do not set parent on cloned item in `createContext`

---

lib/runner/instruction.js
lib/runner/timings.js
npm/build-docs.js

- Marked `Timing` and `Instruction` as `@private`.
- Added support to display examples marked `@private` in the generated documentation.

Marked private examples, tweaked JSDoc build

---

lib/runner/create-item-context.js
lib/runner/extensions/event.command.js
lib/runner/extensions/http-request.command.js
lib/runner/extensions/request.command.js
lib/runner/replay-controller.js
lib/runner/request-helpers-presend.js

* `http-request` extension is now only responsible for request send related responsibilities
* Variable resolution is now the responsibility of `request` extension, there is no need to send all variable types to `http-request` from `event` extension and `replay-controller`.
* Context creation extracted out to be used by anyone scheduling a request with `http-request` extension

Moved variable resolution out of `http-request` extension

---

lib/runner/create-item-context.js
lib/runner/extensions/event.command.js
lib/runner/extensions/request.command.js
lib/runner/replay-controller.js

* General cleanup around `createItemContext` exports and docs
* Reorganize `merge` options with `defaults`

General cleanup in `createItemContext` exports and docs 

---

lib/authorizer/aws4.js

`service` is the defined property for AWSv4 definitions in the v2 postman-collection schema. The fallback was introduced as a fix for `service` not being used [here](https://github.com/postmanlabs/postman-collection/pull/33/commits/8c8146e0f0daaf74c3122af48ed181793ae752ef).
This might create issues when a collection has both `service`(empty - intended to use default) and `serviceName`(an outdated value) the outdated value will be used which is not intended behaviour.

Remove fallback for unsupported property in AWS4 auth

---

lib/authorizer/oauth2.js
test/unit/auth-handlers.test.js

Postman App indicates that duplicate headers will be removed. This behaviour of adding without removing creates two `Authorization` headers.

Remove duplicate headers and query params in OAuth 2.0 before signing

---

lib/runner/extract-runnable-items.js
lib/runner/index.js
test/unit/extract-runnable-items.test.js

**Behavior:**
- Follows the same order as of Postman Collection.
- Picks the first match for an entry point in the collection.
- Ignores nested entry points.
- Bail out if any of the given entry point(s) is not found.
**Benchmark:**
*lookupStrategy: multipleIdOrName*
```
First Match      x 72,505 ops/sec ±19.81% (74 runs sampled)
Last Match       x 62,777 ops/sec ±4.04% (81 runs sampled)
No Match         x 51,929 ops/sec ±4.06% (55 runs sampled)
Deeply Nested    x 67,807 ops/sec ±5.09% (78 runs sampled)
Multiple Matches x 40,379 ops/sec ±3.17% (74 runs sampled)
Nested Matches   x 38,728 ops/sec ±2.55% (80 runs sampled)
```
*lookupStrategy: idOrName*
```
First Match   x 87,271 ops/sec ±12.31% (76 runs sampled)
Last Match    x 74,652 ops/sec ±2.12% (81 runs sampled)
No Match      x 58,218 …
```

Add support for multiple entry points to extract runnable items

---

package.json
test/integration/sanity/http-methods.test.js

Added tests for missing & non-string HTTP method

---

test/fixtures/server.js
test/integration/protocol-profile-behavior/sanity.test.js
test/integration/requester-spec/redirect.test.js
test/integration/sanity/certificate.test.js
test/integration/sanity/redirect.test.js

Removed duplicate code for local redirect server from test files and added it in server.js module.
Also changed URL pattern for redirect server to make it more generic. Previously two patterns were used in different instances of redirect server:
1. /redirect/\<responseCode\>
2. /<n:hops>
Now it only uses one combined pattern:
1. /\<path\>[/<n:hops>/\<responseCode\>]

Added redirect server to separate module in tests

---

test/fixtures/auth-requests.json
test/integration/auth-methods/hawk.test.js
test/integration/sanity/hawk-auth.test.js

Hawk auth tests currently uses 'appId' to refer to app paramter, which isn't recognized by postman-runtime where it's defined as 'app' thus app parameter is not inserted into request headers.

Update Hawk auth tests to use correct identifier for hawk auth app param

---

lib/requester/core.js
lib/requester/requester-pool.js
lib/requester/requester.js
package-lock.json
package.json
test/integration/requester-spec/timing.test.js
test/unit/requester-core.test.js

Added time option to get detailed timing information about different phases of a request. Now you can use {time:<Boolean>} (true by default) in requester options for the same. The timing information will be added in response object returned in Requester.request function's callback.
**Note:** Need to merge https://github.com/postmanlabs/postman-collection/pull/796 first and bump SDK version(beta) for green builds. ✅

Added time option for requester to get detailed timings in response

---

test/integration/auth-methods/control-flow/errors.test.js
test/integration/auth-methods/control-flow/typical.test.js
test/integration/bootstrap.js
test/integration/request-flow/intermediate-requests.test.js
test/integration/sanity/control-flow.test.js
test/integration/sanity/systemproxy.test.js
test/unit/backpack-ensure.test.js
test/unit/backpack-multiback.test.js
test/unit/backpack-normalise.test.js
test/unit/backpack-timeback.test.js
test/unit/runner-util.test.js

Extends #738
- Update bootstrap reset -> restore, reset clears the state whereas restore removes the sinon instance from the function.
- Restores all the spies created in the test to avoid memory leak in Node v6 and below.
- sinon by default is a sandbox instance but it's better to create individual sandbox per test suite to make sure it won't affect others.
- sandbox allows to restore all the spies/stubs created in one go but its better if these functions are restored in their individual `after` block(unlike currently: top level `after`).

Test: restore all sinon spies using sandbox

---

lib/requester/requester.js
test/integration/requester-spec/timing.test.js

- Update `response.responseTime` to `timings.end` i.e, response `end` event.
- Update `timings.start` with runtime's request start time
- Track request start time in offset
- Update all the postman-request offset with runtime overhead
- Track runtime request `done` in offset

Additional request-response timings properties

---

lib/requester/requester.js
test/integration/request-flow/headers.test.js

- Add `connection` system header which is added by Node based on agent option.
- This is also useful for true request size calculation.
- Previously handled by https://github.com/postmanlabs/postman-collection/pull/814 hack.

Added `connection` system header

---

lib/runner/request-helpers-presend.js
lib/runner/util.js

- util.createReadStream: Add the ability to clone read stream
- Load file first in request presend helpers because auth helpers need to reset file stream.
```javascript
var fileReadStream;
// init
util.createReadStream(require('fs'), fileSrc, function (err, stream) {
fileReadStream = stream;
});
// ... read file etc.
// reset
fileReadStream.cloneReadStream(function (err, stream) {
fileReadStream = stream;
});
```

Added ability to clone file read stream

---

lib/authorizer/aws4.js
lib/authorizer/digest.js
lib/authorizer/hawk.js
lib/authorizer/oauth1.js
lib/requester/core-body-builder.js
lib/requester/core.js
package-lock.json
package.json
test/integration/request-flow/unicode-url.test.js
test/unit/requester-core.test.js

- Use postman-url-encoder everywhere
- Use encoded URLs in auth helpers
- Send URL object to postman-request instead of string
- Encode body for URL-Encoded Forms in runtime itself

URL encoding related changes

---

CHANGELOG.yaml
lib/runner/extract-runnable-items.js
test/unit/extract-runnable-items.test.js

Added `followOrder` lookup strategy which supports:
- multiple id or name lookup
- enforce the order to follow
- supports duplicates i.e, iterate the same item multiple times

Added followOrder lookup strategy to extract runnable items

---

CHANGELOG.yaml
README.md
lib/requester/core.js
lib/requester/requester-pool.js
test/integration/requester-spec/maxResponseSize.test.js

- Added `maxResponseSize` requester option which aborts the request if the response size exceeds the threshold
- default: `undefined`

Added maxResponseSize requester option

---

CHANGELOG.yaml
lib/requester/core-body-builder.js
lib/requester/core.js
lib/requester/requester.js
test/integration/request-body/raw.test.js
test/integration/request-flow/headers.test.js

- Refactored requester to avoid duplicate computation for response object
- Fixed a bug where non-string raw bodies crash the process https://github.com/postmanlabs/postman-app-support/issues/6651
- Fixed a bug where disabled headers with the same name as of system headers don't get overwritten in the original request

Refactored requester to avoid duplicate computation for response object

---

CHANGELOG.yaml
lib/requester/core.js
test/integration/request-flow/resolve-localhost.test.js
test/unit/requester-core.test.js

Resolve all `*.localhost` addresses to `127.0.0.1` by overriding lookup function.
RFC: [6761 section 6.3](https://tools.ietf.org/html/rfc6761#section-6.3)
Ref: https://github.com/postmanlabs/postman-app-support/issues/2638

Override lookup function for *.localhost

---

CHANGELOG.yaml
lib/requester/requester.js
test/integration/request-flow/headers.test.js

Correctly update system headers in case of multiple headers with came key (`Cookie`) are present.
Bug: Previously it used to just update the last item in the list.
Fix: Remove all duplicates and just keep the final change.

Handle duplicate system headers addition

---

lib/requester/requester.js

- Update history object to always have the session data (previously reused session are not stored).
- An ideal solution should be to cache all the sessions in the requester's socket pool and fetch session details from there. (TODO)

Always add reused session data to history object

---

CHANGELOG.yaml
README.md
lib/runner/extensions/event.command.js
package-lock.json
package.json
test/integration/sandbox-libraries/console.test.js

This change allows preserving non-JSON data types in console logs. It also adds
an option `script.serializeLogs` to allow sending logs as a serialized string
which can be parsed using `teleport-javascript` library.

Add option `script.serializeLogs` to send serialized logs

---

CHANGELOG.yaml
lib/authorizer/ntlm.js
test/integration/auth-methods/ntlm.test.js

Tests have been verified to run perfectly with a locally setup NTLM server.

Fix throwing of error on empty NTLM parameters

---

CHANGELOG.yaml
lib/authorizer/ntlm.js
test/fixtures/server.js
test/integration/auth-methods/ntlm.test.js

Also added a local NTLM server which sends `www-authenticate: Negotiate` along with type2 message. Adding this takes care of this bug.

Update NTLM auth to find correct type2 header before parsing

---

CHANGELOG.yaml
lib/authorizer/oauth2.js
test/unit/auth-handlers.test.js

- Treat non-Bearer OAuth2 tokens(except MAC) as Bearer tokens.
Solves: https://github.com/postmanlabs/postman-app-support/issues/5434

Non-bearer OAuth2 tokens

---

CHANGELOG.yaml
lib/runner/extensions/waterfall.command.js
lib/runner/index.js
test/integration/runner-spec/iterationCount.test.js
test/unit/runner.test.js

If iteration count is more than the length of `data`, the `normaliseIterationData` function fills the `data` array with the last element in `data` such that `data.length = iterationCount`.
When iteration count is a large number (e.g. 99999999), run creation takes a lot of time and sometimes even fails with "Out of Memory" error because the JS Heap is exhausted.
This change avoids the above situation by simply setting the `data[iterationCount - 1]` element as the value to be repeated. Later, when iteration data is to be fetched, if the element at `data[iteration]` exists, we use it; if not, we use the last element of the `data`.
---
For `iterationCount` 9999999, time for `run` creation:
- 3s 417ms
- 3s 403ms
- 3s 505ms
- 0s 2.1ms
- 0s 1.9ms
- 0s 1.9ms

Avoid OOM in `normaliseIterationData`

---

lib/requester/core.js
test/integration/protocol-profile-behavior/sanity.test.js

Added new `protocolProfileBehavior` property to disable cookie jar for an individual request.

Added request setting to disable cookies

---

test/integration/runner-spec/iterationCount.test.js
test/unit/runner.test.js

Add a test that check if run creation is successful for large iteration count. Not checking if iterations are run because it'll take a looong time.

Add test for large iteration count

---

CHANGELOG.yaml
lib/requester/requester.js
test/integration/request-flow/response-cookies.test.js

Fixed a bug where cookies in `response` callback were having `null` expiry when the cookie received from the server only had `Max-Age` field without `Expires` field.
Fixes: https://github.com/postmanlabs/postman-app-support/issues/7738

Fixed expiry of cookies with `Max-Age` field

---

CHANGELOG.yaml
lib/authorizer/oauth1.js
package-lock.json
package.json
test/integration/auth-methods/oauth1.test.js

Parameters in OAuth1 Authorization header were percent-encoded by default. This PR adds an option to toggle percent-encoding while generating Authorization header for OAauth1.
Todo:
Issues:
- https://github.com/postmanlabs/postman-app-support/issues/3999
- https://github.com/postmanlabs/postman-app-support/issues/4300
- https://github.com/postmanlabs/postman-app-support/issues/5744

Added an option in OAuth1 to toggle parameter encoding in Authorization header

---

CHANGELOG.yaml
lib/authorizer/aws4.js
test/unit/auth-handlers.test.js

Changed updated headers in AWS auth manifest.
**Old headers:**
- Host
- Authorization
- X-Amz-Date
- X-Amz-Security-Token
- Content-Length
- Content-Type
**New headers:**
- Host
- Authorization
- X-Amz-Date
- X-Amz-Security-Token
- X-Amz-Content-Sha256

Fixed request headers updated by AWS auth in manifest

---

lib/requester/core.js
test/integration/request-body/form-data.test.js

Fixes a bug where `content-type` header was sent even if all the params are disabled.

Handle disabled formdata and urlencoded body

---

lib/requester/core-body-builder.js
test/integration/request-body/graphql.test.js
test/integration/request-body/raw.test.js

Fixes a bug where the system added `content-type` header was not added when the given header is disabled.

Handle disabled content-type for raw and graphql body

---

CHANGELOG.yaml
lib/requester/core.js
lib/requester/dry-run.js
lib/requester/requester.js
package-lock.json
package.json

`dryRun` method is used to live preview request headers, query params, etc.

Added method Requester~dryRun

---

CHANGELOG.yaml
lib/authorizer/oauth1.js
test/integration/auth-methods/oauth1.test.js
test/unit/auth-handlers.test.js

- exclude disabled url params and disabled url-encoded body params while calculating OAuth1 signature
Issue: https://github.com/postmanlabs/postman-app-support/issues/7522

Fixed OAuth1 signature calculation for request with disabled urlencoded params

---

lib/requester/core.js
lib/requester/requester-pool.js
test/unit/requester-core.test.js

This first of two PRs aimed to address the need to run postman tests via socks proxy. It is a long-standing request documented here: postmanlabs/postman-app-support#1321.
The proposed first (minimum viable) step is to allow teams that use newman as a library to pass their own HTTP agent through to postman request. Postman request already supports agent option. This would enable use of libraries like socks-proxy-agent to run tests through socks proxy.
Please let me know if you need additional information.

Pass agent option through to postman-request

---

CHANGELOG.yaml
lib/authorizer/oauth2.js
test/unit/auth-handlers.test.js

In OAuth 2.0,
- `headerPrefix` field will allow overriding Authorization header prefix
- If not provided (null or undefined), prefix `Bearer ` will be used by default
Issues:
- https://github.com/postmanlabs/postman-app-support/issues/4727
- https://github.com/postmanlabs/postman-app-support/issues/6616

Added support for using custom Authorization header prefix in OAuth 2.0

---

CHANGELOG.yaml
lib/authorizer/digest.js
package-lock.json
package.json
test/unit/auth-handlers.test.js

- Added support for following algorithms in Digest auth
1. SHA-256
2. SHA-256-sess
3. SHA-512-256
4. SHA-512-256-sess
- Removed `crypto-js` form dependencies
- Added `js-sha512` dependency for SHA-512-256 algorithm
Issue: https://github.com/postmanlabs/postman-app-support/issues/5265

Added support for SHA256 algorithm in Digest auth

---

CHANGELOG.yaml
lib/requester/dry-run.js

Fixes a [bug](https://github.com/postmanlabs/postman-app-support/issues/8348) where cookies are not previewed when URL is resolved from a variable.

Fetch cookies on `Requester~dryRun` using the encoded URL object

---

CHANGELOG.yaml
lib/requester/dry-run.js

Only headers should be treated as case insensitive not the query params and urlencoded body params. This was causing problems for added query params by AWS auth helper because added params contain uppercase letters and SDK treats params as case-sensitive.
Discovered this as a part of https://github.com/postmanlabs/postman-runtime/pull/1041

Treat query params and body params as case sensitive in `dryRun()`

---

CHANGELOG.yaml
lib/authorizer/oauth1.js
test/unit/auth-handlers.test.js

OAuth1 throws error when selected algorithm is RSA and the given private key is invalid. This was causing problem in `dryRun()` method which is properly handled now.

Handle invalid private key errors in OAuth1 RSA signatures

---

CHANGELOG.yaml
lib/authorizer/digest.js
test/integration/auth-methods/digest.test.js
test/unit/auth-handlers.test.js

Fixed a bug where digest auth was not generating correct Authorization header when `qop` field was set to `auth-int`. It was due to improper body hash calculation.

Fixed body hash calculation in Digest auth

---

CHANGELOG.yaml
lib/authorizer/oauth1.js
test/unit/auth-handlers.test.js

Don't include empty callback and verifier fields in the OAuth1 signature calculation. It creates invalid signature problem for servers that don't support those parameters.
Issue: https://github.com/postmanlabs/postman-app-support/issues/8737

OAuth1 signature fix for empty callback and verifier fields

---

CHANGELOG.yaml
README.md
lib/requester/core.js
lib/requester/requester-pool.js
test/integration/requester-spec/systemHeaders.test.js

new config: `systemHeaders` (part of `requester`)
These headers cannot be disabled or overridden and are added with `system` flag set to true.
Code changes:
Added a new function `addCustomSystemHeaders` which is called from `getRequestOptions()`. This function adds all the headers to `request.headers` object and updates any header if it is already present.

Added a new requester config to add custom system headers

---

CHANGELOG.yaml
lib/requester/core.js
test/integration/bootstrap.js
test/integration/protocol-profile-behavior/tlsProtocols.test.js

Changed the maxVersion when TLSv1.3 is to be disable, since secureOptions does not support it in node 12

Added option to allow disabling TLS v1.3

---

CHANGELOG.yaml
docs/history.md
lib/requester/browser/request.js
lib/requester/requester.js
package-lock.json
package.json
test/integration/request-flow/headers.test.js
test/integration/request-flow/pm-send-request-cookies.test.js
test/integration/requester-spec/history.test.js
test/integration/requester-spec/redirect.test.js
test/integration/sanity/cookie-handling.test.js
test/integration/sanity/file-uploads.test.js

Add request and response headers to history object. 
Update the `addMissingRequestHeaders()` function to add headers from history.
Fixed a bug where in case of redirects, the request object in callbacks, had headers which were not present in the first request.

Updated history object to include headers

---

lib/authorizer/oauth1.js
test/integration/auth-methods/oauth1.test.js
test/unit/auth-handlers.test.js

TASK: Fix the Incorrect Signature Generation for URLs with Encoded Query Parameters
Implementation: Updated the message being sent to `node-oauth1` for signature generation. Added query parameters to action of this message by adding path instead of pathname in `getOAuth1BaseURL`. Removed queryParams from allParams which is passed to `node-oauth1` for signature generation.
Added a function to re-encode the query parameters to RFC-3986 and update these in the request being sent. This function uses formDecode and percentEncode from `node-oauth1`. `formDecode` breaks the query string down and decodes it with `decodePercent`, so that we can encode it again with `percentEncode` to the RFC-3986 standards and update the request. It correspondingly removes parameters from the request and adds the …

Fix OAuth1.0a Incorrect Signature for URL Encoded Params

---

CHANGELOG.yaml
lib/requester/requester.js
test/fixtures/servers/http.js
test/integration/sanity/cookie-handling.test.js

`CookieList` was populated with initial request's cookies instead of the final request sent in a redirect chain.

Fixed CookieList in request and response callback on redirects

---

lib/authorizer/auth-interface.js
lib/authorizer/oauth1.js
lib/runner/request-helpers-presend.js
test/integration/auth-methods/oauth1.test.js
test/unit/auth-handlers.test.js

**Task**: Update Authorizer to respect protocolProfileBehavior.disableUrlEncoding option
**Implementation**: Pass the protocolProfileBehaviour in `request-helpers-presend` in `createAuthInterface`. This is assigned to a private property `_protocolProfileBehavior` in `AuthInterface`, which defaults to `{}` when not passed.  Update Auth Handlers where parameter encoding is updated (only in OAuth1) to encode params according to this setting.
Add unit tests for the `sign` method in OAuth1 for this option and integration tests to make sure the setting is repsected.

Respect Request Encoding Option in Authorizer

---

.nycrc.js
lib/authorizer/asap.js
lib/authorizer/index.js
package-lock.json
package.json
test/fixtures/get-auth-requests.js
test/integration/auth-methods/asap.test.js
test/unit/auth-handlers.test.js

This adds functionality to send requests with Atlassian's S2S Authentication Protocol, or ASAP auth
https://s2sauth.bitbucket.io/spec/

Added support for ASAP auth

---

lib/authorizer/digest.js
test/fixtures/auth-requests.json
test/unit/auth-handlers.test.js

As per [RFC-6617](https://datatracker.ietf.org/doc/html/rfc7617#section-2), the scheme and parameters should be handled case-insensitively.
As part of this PR I have removed the case sensitive checks
issue link - https://github.com/postmanlabs/postman-app-support/issues/12727

Remove case sensitivity check for scheme and parameters name in Digest Auth

---

CHANGELOG.yaml
lib/requester/requester.js
lib/runner/extensions/event.command.js
test/integration/request-flow/requests-from-sandbox.test.js
test/integration/sanity/url-sanity-before-request.test.js

Issue:
Errors from pm.sendRequest, when transmitted out of postman-runtime didn't have the complete message, stack trace and other related information. This happened because of sending the error object inside the sandbox using messagePort lost certain information during serialization.
Fix:
Serialize error (convert to plan JS object) to make it safe for transmission across different realms.

Serialised errors received on executing pm.sendRequest

---

lib/runner/util.js
test/integration/sanity/vaultSecrets.test.js

This PR addresses the issue where vault secrets were not being resolved when using a hostname that contains port. The problem was caused by incorrect domain matching in the variable resolution process.
Changes made:
Updated the URL pattern generation in lib/runner/util.js to correctly handle domains with and without ports.
Added tests
This fix should resolve the issue reported in the community post:
https://community.postman.com/t/using-vault-sends-values-as-vault-token-instead-of-real-value/68970

Fix domain matching for Vault variables

---

CHANGELOG.yaml
lib/runner/extensions/event.command.js
test/integration/sanity/variable-changes.test.js
test/integration/sanity/vaultSecrets.test.js

This PR refactors how vault access is handled in the event command extension:
Renames allowVaultAccess to isVaultAccessInScriptsAllowed for clarity
Moves vault access check and tracking enablement into the vault execution handler
Adds support for isVaultAccessInScriptsAllowed to be either a boolean or an async function
Updates vault access check to use the new isVaultAccessInScriptsAllowed approach

Refactor vault access handling in event command

---

README.md
lib/requester/core.js
lib/requester/requester-pool.js
test/fixtures/servers/_servers.js
test/fixtures/servers/dynamicHeadersHTTP1.js
test/fixtures/servers/dynamicHeadersHTTP2.js
test/integration/requester-spec/maxHeaderSize.test.js

This introduces the `maxHeaderSize` option for limiting HTTP header size in Node.js HTTP/1 requests. It includes implementation, tests for various scenarios, and updates to documentation. The feature is ignored for HTTP/2 where header sizing is not configurable.

feat: Add support for configurable maxHeaderSize in HTTP requests

---

CHANGELOG.yaml
lib/authorizer/digest.js

Works to fix https://github.com/postmanlabs/postman-app-support/issues/13756
Since servers can return multiple values for `www-authenticate` headers to present clients with multiple options, we need to filter the right header based on the `auth.algorithm` setting passed by `postman-runtime`'s consumer.

fix: Multiple digest auth headers not filtered by opted algorithm

---

CHANGELOG.yaml
lib/runner/nested-request.js
test/integration/runner-spec/run-collection-request.test.js

- Replaces the `abortOnFailure` prop to nested requests with `stopOnError` prop.
- Adds tests to ensure there are no aborts due to failures in nested request's script assertions.

fix: Nested Requests aborting execution on error in scripts
